AICONSlab/MIRACL

docs/install-local.md
updated download link for local installation
=> updated link

miracl/conv/miracl_conv_set_orient_gui.py, miracl/flow/miracl_workflow_sta.sh, miracl/miraclGUI.py, miracl/seg/miracl_seg_clarity_neurons_wrapper.sh, miracl/seg/miracl_seg_neurons_clarity_3D_cfos2.ijm, miracl/seg/miracl_seg_voxelize_parallel.py, miracl/sta/miracl_sta_create_force_graph.py, miracl/utilfn/miracl_utilfn_extract_lbl.py
- added "dilation" feature that allows users to dilate regional mask when using STA workflow
- updated STA workflow to work from end to end
- updated orientation setting tool in registration workflow to display images in order
- fixed bug in segmentation GUI that set input to nested directory
- set default segmentation to cfos2
- set correct paths in cfos2 segmentation macro
- removed '_bin' from voxelization script
- fixed typos
=> Updates to STA Workflow, Segmentation Tools

miracl/reg/miracl_reg_clar-allen.sh, miracl/sta/miracl_sta_gen_tract_density.py, miracl/sta/miracl_sta_track_primary_eigen.py, miracl/sta/sta_gui.py
This minor patch fixes an error in the GUI where the STA fields caused the app to close
=> Sta workflow

miracl/lbls/miracl_lbls_stats.py, miracl/sta/miracl_sta_gen_tract_density.py
Integrating tract ratio statistics in 'miracl lbls stats' function. Tract ratios can be calculated using the '-r, --ratio' flag.
=> [feat] Tract ratio stats integration

.circleci/config.yml, Dockerfile, setup.py
Major fixes:
- Registration script in CLI
- STA workflow in CLI
- setuptools issue
=> Re-release v2.2.2

miracl/seg/ace_deploy_model.py
since the weights of the model is float, we needed to have the same dtype.
=> [fix] change input type to float

miracl/seg/ace_patch_stacking.py
I fixed all the issues. In this version, the image depth, width and height are calculated automatically, so the user doesn't need to give them as input. There were some typos in the filename, causing saving errors that are solved in this version
=> [fix] troubleshooting

miracl/flow/ace_test_interface_abstract.py, miracl/flow/miracl_workflow_ace_parser.py, miracl/flow/miracl_workflow_ace_stats.py, miracl/stats/miracl_stats_voxel_wise.py
Change wild --> control and disease --> experiment. Makes the difference between the two groups more clear.
=> [fix] Rename wild and disease groups

miracl/flow/ace_test_interface_abstract.py
Bugfix: incorrect args were passed to `ACECorrelation.correlate()`. Static method fetches correct nifti files from `clust_final`, i.e. assigns absolute path to var, and checks if they exist. Raises error if False, otherwise args can be passed to `ACECorrelation.correlate()`.
Has been tested by invoking ACE interface manually with mock data but writing unit tests should be a priority for next PR.
=> [fix] fetch, test and forward correct args to correlate fn

miracl/flow/miracl_workflow_ace_interface.py, miracl/flow/miracl_workflow_ace_parser.py, miracl/reg/miracl_reg_warp_clar_data_to_allen.sh
- Added correct args for warping and voxelizing.
- Cleaned up warping script a bit. Needs more cleaning before release.
- Ran Black formatter on interface.
=> [fix] implement correct args for warping and voxelizing

.circleci/config.yml
- Update singularity commands to build container locally based on docker image
- Add dev branch CICD workflows
- Dev branch will push dev docker image and build a singularity image (without pushing it)
=> Singularity and CICD Fix

docs/index.rst, docs/notebooks/notebooks.rst, docs/tutorials/registration/clarity_allen/clarity_allen.rst
Add 'Notebooks' section to the sidebar for direct download access of the Jupyter notebooks.
=> [docs] add Notebooks section to sidebar

docs/tutorials/slurm/compute_canada/compute_canada.rst
This PR addresses an unnecessary `git submodule` that was added in a previous PR.
The PR also squashes all the commits from the previous PR into a single commit since all the commits were small changes to our docs.
=> Fix dev branch from latest PR

docs/downloads/data/example_and_atlases_data/example_and_atlases_data.rst, docs/tutorials/stats/ace_cluster/ace_cluster.rst, docs/tutorials/workflows/ace_flow/ace_flow.rst
Download script implemented for easier user experience. Must add instruction to docs for user to know how to use the script.
=> [docs] Update ace docs to use download script

docs/installation/installation.rst, docs/tutorials/stats/ace_cluster/ace_cluster.rst, docs/tutorials/workflows/ace_flow/ace_flow.rst
- Fix bullet point formatting
- Fix spelling mistake on install doc page
=> [docs] Fix formatting for bullet points

docs/tutorials/workflows/ace_flow/ace_flow.rst
=> [docs] Update ace_flow.rst

docs/tutorials/workflows/ace_flow/ace_flow.rst, miracl/seg/ace_finetune_model.py, miracl/seg/ace_finetune_model_config.yml, miracl/seg/cli_seg.py, setup.py
Completed:
- Add script for finetuning ace models
- Add config file for fine-tuning hyperparams
- Add fine-tuning to the `miracl seg` CLI
- Update ACE docs to contain information on fine-tuning
- Also tested the script with @AAttarpour data and all is working well
=> Add ACE Finetuning Script

.gitignore, docs/conf.py, docs/installation/installation.rst, docs/tutorials/workflows/ace_flow/ace_flow.rst
These changes to the docs accompany the changes to the installation script from #155 based on the feedback provided by @Andrew-Clappison .
=> [docs/feat] improve docs based on user feedback

install.sh
Fixed the installation script errors.
=> Third round of Andrew's feedback on ACE

README.md
=> [fix] fix incorrect link to CC website

docs/installation/installation.rst
Increment version number for Apptainer direct download link to… latest MIRACL version.
=> [PR] small docs fix into `dev`
