- miracl/sta/cli_sta.py
- This patch fixes a bug in the STA workflow, where a reference is made to a function that doesnt exist
> minor patch: updating reference in STA cli

- .circleci/config.yml
- Dockerfile
- miracl/sta/miracl_sta_gen_tract_density.py
Fix three issues that prevented compilation of Docker image and access to interactive shell session in Docker container.
[fix] fix broken Python library import: Import of 'trackvis' from 'nibabel' in file 'miracl_sta_gen_tract_density.py' would break with the following error message: cannot import name 'trackvis' from 'nibabel'. Fix by using prefix 'nib' for 'trackvis' call like so: 'nib.trackvis'.
[fix] change entrypoint for Docker container: 'ENTRYPOINT ["/opt/miniconda/bin/miracl"]' in 'Dockerfile' would not allow for interactive shell access and result in error prompting for valid MIRACL arguments when running 'docker run -it mgoubran/miracl bash'. Fix by uncommenting entrypoint line in Dockerfile.
[fix] modify CircleCI test case for docker: After removing the …
> [fix] fix issue with py lib and Dockerfile

- docs/index.rst
- docs/install-windows.md
[docs] add doc entries for Windows install: adding the docs section for local MIRACL installation for Windows using WSL2. Doc entries were written and integrated by entiri.
> [docs] adds doc entries for Windows install

- docs/install-windows.md
Correct minor spelling mistake and formatting for Windows installation doc entry headers. One '#' was used for some headers when two should have been used to make them sub-headers.
> [docs] correct formatting and spelling of Win doc entries

- docs/install-docker.md
- docs/install-singularity.md
miraclGUI does not work when executed in a Docker container locally or in a Singularity container on a SLURM cluster. Several troubleshooting steps have been added to the install-singularity.md and install-docker.md docs as a workaround.
> [docs] Add troubleshooting steps to docs for GUI issue

- miracl/reg/cli_reg.py
Corrected string input formatting error for mri-allen-reg and mri-nifty-allen-reg in cli_reg.py which expect string input for certain flags. Currently a working pull request to establish that some changes need to be made for niftyreg and regular mri-allen-ants reg scripts to work.
> [fix] correct string formatting syntax error in cli_reg.py

- miracl/lbls/miracl_lbls_stats.py
- miracl/sta/miracl_sta_gen_tract_density.py
Nibabel's method 'nibabel.trackvis.read' has been deprecated from version 2.5.0. It has been replaced with 'nibabel.streamlines.load' which returns an object that can't be assigned in parallel as it was done in the original code in which the object 'nibabel.trackvis.read' was returned. The deprecated method has been replaced and the syntax has been changed accordingly in 'miracl_sta_gen_tract_density.py' and 'miracl_lbls_stats.py'.
> [fix] replace deprecated nibabel.trackvis.read

- miracl/stats/miracl_plot_single_subj.py
From Seaborn version 0.12, the only valid positional argument will be 'data'. Passing other arguments without an explicit keyword will result in an error or misintertpretation. Fixed by explicitly passing x, y variables as keyword arguments to sns.barplot() call.
> [fix] fix Seaborn positional arguments problem

- .circleci/config.yml
Docker base-image should not be pushed to Docker Hub as it has not been changed in CircleCI build process. Kept in the CircleCI config file if it needs to be reintegrated at some point.
> [fix] remove push of Docker base-image

- .readthedocs.yaml
readthedocs builds were failing (see explanation below). This adds a `.readthedocs.yaml` file to the project root that fixes this issue.
From the readthedocs website:
> We are announcing a new requirement for all builds to use our configuration file version 2. This announcement deprecates builds without a configuration file, as well as version 1 of our configuration file.
>
> Read the Docs will start requiring a `.readthedocs.yaml` configuration file for all projects in order to build documentation successfully. We will stop supporting builds without explicit configuration, because this creates implicit dependencies that users aren’t aware of. We plan to start failing builds not using configuration file version 2 on September 25, 2023.
> [fix] add yaml config file to fix failed readthedocs build

- miracl/flow/ace_test_interface_abstract.py
- miracl/flow/miracl_workflow_ace_parser.py
Add overwrite flag for the comparison workflow of ACE. This forces the workflow to skip over the steps that are for single subjects (seg, conv, reg, vox, warp) and assumes (with checks) that these steps have already been performed. It then will perform only the comparison-based steps of the workflow (cluster, correlation, heatmap). 
This allows the user to skip the computation-intensive steps of the workflow once they have already been performed once. If one wants to just re-run the comparison-based steps, they can do so.
> Add overwrite flag for ACE

- miracl/flow/miracl_workflow_ace_parser.py
- miracl/reg/miracl_reg_warp_clar_data_to_allen.sh
Parsing and in particular the channel argument were incorrectly implemented in the warping fn. The warping function can also be integrated into the ACE workflow now using "ace_flow" as the channel arg. "green" has been removed as the default string in the ACE interface parser.
Important: the warping fn should be integrated into the ACE workflow by passing "ace_flow" as an argument in the interface.
Note: warping script needs to more cleaning up (removing comments etc.) before next MIRACL release
> [fix] fix clar allen warping fn

- docs/installation/installation.rst
- docs/tutorials/stats/ace_cluster/ace_cluster.rst
- docs/tutorials/workflows/ace_flow/ace_flow.rst
- miracl/flow/miracl_workflow_ace_interface.py
- miracl/flow/miracl_workflow_ace_parser.py
- miracl/miraclGUI.py
1. Minor doc changes
2. Small bugs that came up when testing ACE
- Update ACE documentation so that the example commands work for the sample data we have
- Add more details on how to get the ACE model files in the right location
- Ensure that the warp file always overwrites any existing warp file (before it would raise an error if a warp file already existed)
- Update the glob pattern to search for the existing conversion file. The glob would not work with single-digit downsample ratios
- Add printing of default vox downsample ratio in parser help
- Change the group for arg `--sa_percentage_brain_patch_skip` (used for skipping empty brain patches). It did not belong to the right parser group (seg) so it was not showing up.
- Update MIRACL GUI icon path to display the image in GUI mode
- …
> Finalize ACE docs and Minor Bugs

- docs/installation/installation.rst
- docs/tutorials/stats/ace_cluster/ace_cluster.rst
- docs/tutorials/workflows/ace_flow/ace_flow.rst
- install.sh
Items completed
- Swap ACE single subject and ACE stats commands that were in the wrong spots
- Add explanation that docker is mounting `miracl/` by default
- Change the example code to contain only full-length flags
- Change the batch size for ACE example code
- Add explicit GPU flag on the installation page
- Change sample data download to HuggingFace
> Small fixes for ace docs

- install.sh
Instead of using the -d flag to set the memory size that is shared between containers, the flag now sets the max memory limit for the container itself. For that the script first checks whether the host machine is running Linux or MacOS and uses the appropriate command to set 85% of available memory as a default.
> [feat] replace shm_size with mem_limit

- install.sh
The `docker-compose.yml` needs shm option since the ACE dataloaders rely on shared memory.
> [fix] Add shm back to install script

- README.md
- docs/index.rst
- docs/tutorials/workflows/ace_flow/ace_flow.rst
- Update old ACE links pointing to `ace` branch
- Links points to main GitHub page now
> [docs] Fix stale ACE links

- miracl/flow/miracl_workflow_ace_interface.py
Voxelization in the comparison workflow was missing an argument. The single workflow has the right arg there, but not the comparison workflow.
> [bugfix] Voxeliztion missing arg

- setup.py
Python's typer package is automatically being installed as part of PyTorch. However, the Typer version installed was > 0.12.0 which changed its dependency structure, removing the need for typer[all]. After version 0.12.0, the typer package uses typer-slim[standard] which includes the default dependencies, instead of typer[all]. This introduced breaking changes to MIRACL and the installed version of PyTorch. Pinning the version to 0.11.1 solved the issue. Also moved up torchio to more clearly cluster it with other PyTorch packages.
> [fix] pin typer to 0.11.1 to fix MIRACL breaking changes introduced by ACE

- README.md
- docs/tutorials/workflows/ace_flow/ace_flow.rst
- install.sh
There will be more commits added to this PR (don't review yet!) but generally speaking this should include all of the changes that were required after getting Andrew's feedback from his testing sessions.
> Second round of changes to Andrew's feedback

- .circleci/config.yml
- README.md
- docs/index.rst
- docs/installation/installation.rst
- docs/troubleshooting/index.rst
- docs/troubleshooting/troubleshooting_apptainer.rst
- docs/tutorials/slurm/compute_canada/compute_canada.rst
- docs/tutorials/slurm/index.rst
- docs/tutorials/slurm/sherlock/sherlock.rst
- docs/tutorials/workflows/ace_flow/ace_flow.rst
- utility_scripts/download_sample_data
Now that ACE has been released, we need to be more agile to quickly respond to issues and user requests. The biggest bottleneck currently is building and uploading Singularity images. This requires a new token every month and we have a maximum traffic limit for builds that restricts our MIRACL releases to <5/month. In the longterm we need to find a better hosting solution and also a different way to build the sif files that does not come with restrictions. However, for now I am disabling the Singularity build/upload completely in the CircleCI workflow as a short term solution. This will make publishing new MIRACL releases easier and more agile but we will also have to manually build and upload Singularity images for the time being.
Don't approve this PR yet please. Instead, let's add the …
> [feat] disable Singularity build/upload in CircleCI workflow

- miracl/reg/cli_reg.py
- miracl/reg/miracl_reg_clar-allen.sh
- miracl/reg/miracl_reg_clar-allen_utility.py
This fixes several major issues in the Clarity Allen registration script:
1. Channel prefix and number are now flags in the Clarity Allen registration method. This is necessary for registrations of scans that used channel prefix and number for conversion (e.g. LaVision). Before this would fail as the registration script had no method to differentiate between e.g. autoflor and signal channels in the RAW tif folder delimited by the channel prefix/number combination.
2. The tif stack extraction uses `tifffile` now instead of `c3d`. The latter was failing with larger tif files (e.g. SMARTSpim vs. LaVision). Debugging/profiling indicated that larger files (SMARTSpim) triggered parallel processing in `c3d` which potentially lead to race conditions that weren't apparent when extracting smaller …
> [PR/fix/feat] fix Clarity Allen registration

- miracl/reg/miracl_reg_clar-allen.sh
The logic to check whether the olfactory bulb should or shouldn't be removed was incorrect. It would always evaluate to false since it would only check for an empty flag or a None value. Adding a check for 0 fixed the problem. Another issue is that the olfactory bulb templates are
hardcoded to 25vox. This needs to be fixed as well. A ticket has been opened internally.
> [PR/fix] CLAR Allen Olfactory bulb fix
